// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaR7_eXRWHGwmSYtez_FRw2NKG_Vp30LA',
    appId: '1:1087969207416:web:ffb9b9ca434019178af98d',
    messagingSenderId: '1087969207416',
    projectId: 'tracelink-main',
    authDomain: 'tracelink-main.firebaseapp.com',
    storageBucket: 'tracelink-main.firebasestorage.app',
    measurementId: 'G-NX3D0H65DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqNWyo-k6qG4nmJH4BbtYhc6Ks6J_lqc',
    appId: '1:1087969207416:android:4fccda7e6823c0058af98d',
    messagingSenderId: '1087969207416',
    projectId: 'tracelink-main',
    storageBucket: 'tracelink-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9PySERy_WmR7CIRWHRaDk34T4JL8XMHo',
    appId: '1:1087969207416:ios:b53aff868cfba74c8af98d',
    messagingSenderId: '1087969207416',
    projectId: 'tracelink-main',
    storageBucket: 'tracelink-main.firebasestorage.app',
    iosBundleId: 'com.example.tracelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9PySERy_WmR7CIRWHRaDk34T4JL8XMHo',
    appId: '1:1087969207416:ios:b53aff868cfba74c8af98d',
    messagingSenderId: '1087969207416',
    projectId: 'tracelink-main',
    storageBucket: 'tracelink-main.firebasestorage.app',
    iosBundleId: 'com.example.tracelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaR7_eXRWHGwmSYtez_FRw2NKG_Vp30LA',
    appId: '1:1087969207416:web:20ca4f7fdc8916708af98d',
    messagingSenderId: '1087969207416',
    projectId: 'tracelink-main',
    authDomain: 'tracelink-main.firebaseapp.com',
    storageBucket: 'tracelink-main.firebasestorage.app',
    measurementId: 'G-RX2PM5Z3VH',
  );
}
